### ISSUE TITLE
RSS unreadable

### ISSUE THREAD

**Issue by PiRomant** [catppuccin/qbittorrent#11]
RSS lists is unreadable.
Blue on dark blue and very dark blue on dark blue.
![image](https://github.com/catppuccin/qbittorrent/assets/29551044/855b2fed-d139-4a81-ae12-9cf6d44e8ab6)

**Comment by CocoaTakasaki** [comment]
Could you fix this problem? 
https://github.com/catppuccin/qbittorrent/issues/9
