### ISSUE TITLE
v2.0.0 doesn't work on Windows (?)

### ISSUE THREAD

**Issue by ararezaee** [catppuccin/qbittorrent#19]
Non of the variants load, reverted back to previous version

**Comment by sgoudham** [comment]
Hey :wave:,
That's unfortunate to hear :/ 

Can you tell me the exact steps you took to import the new theme and can you copy/paste the "Software Used" section by going into **Help** -> **About** -> **Software Used**:

![image](https://github.com/user-attachments/assets/17de7e23-913e-43bf-b8ce-f998cb26ef67)

**Comment by theahmadhiwa** [comment]
Same issue. 

These are the software libraries:
Qt: 6.4.3
Libtorrent: 1.2.19.0
Boost: 1.86.0
OpenSSL: 1.1.1w
zlib: 1.3.1

**Comment by sgoudham** [comment]
Does it output any sort of error message or anything? 
And have you made sure to restart the app after choosing the theme file?

**Comment by theahmadhiwa** [comment]
> Does it output any sort of error message or anything? And have you made sure to restart the app after choosing the theme file?

No, there are no error messages of any sort. 
I've restarted the app and even re-downloaded the same and a different theme to make sure, still no luck.

**Comment by sgoudham** [comment]
What version of qBittorent are you using and what operating system?

**Comment by theahmadhiwa** [comment]
> What version of qBittorrent are you using and what operating system?

qBittorrent v4.6.6 (64-bit), Windows 10

**Comment by sgoudham** [comment]
Thanks, aside from the minor differences in the software used to compile the theme, the only difference is the underlying operating system since I compiled the theme on Linux instead of Windows.

I'll get around to testing on Windows but I won't have access to a Windows machine until later today.

I'd appreciate if you could also tell me the version of qBittorent that you're using and the operating system that you're running on @ararezaee @cavalrymargarine0x1.

**Comment by ararezaee** [comment]
Qt: 6.4.3
Libtorrent: 2.0.11.0
Boost: 1.86.0
OpenSSL: 1.1.1w
zlib: 1.3.1

Windows 11 24H2 26100.1591

**Comment by sgoudham** [comment]
@arminius-smh kindly tested out the theme compiled with `rcc 5.15.14` and reported that theme was working fine both on Linux and Windows. 

I used `rcc 6.2.4` for the v2.0.0 release so this may be the reason why.

I've compiled the following `.qbtheme` files in the zip with `rcc 5.15.3`, could you please let me know if these work for you? @ararezaee @theahmadhiwa 

[catppuccin themes compiled with rcc 5.15.3](https://github.com/user-attachments/files/16829941/themes.zip)

**Comment by ararezaee** [comment]
> @arminius-smh kindly tested out the theme compiled with `rcc 5.15.14` and reported that theme was working fine both on Linux and Windows.
> 
> I used `rcc 6.2.4` for the v2.0.0 release so this may be the reason why.
> 
> I've compiled the following `.qbtheme` files in the zip with `rcc 5.15.3`, could you please let me know if these work for you? @ararezaee @theahmadhiwa
> 
> [catppuccin-themes-qbittorrent.zip](https://github.com/user-attachments/files/16829951/catppuccin-themes-qbittorrent.zip)

Can confirm they are all working perfectly

**Comment by sgoudham** [comment]
Thanks for confirming and thanks again to @arminius-smh for figuring out the underlying issue before I could get a chance to investigate myself!

I've re-uploaded the theme files in the v2.0.0 release so hopefully future Windows users won't need to come to this issue.
