### ISSUE TITLE
Neutral Dark Color Request

### ISSUE THREAD

**Issue by fossist** [catppuccin/qbittorrent#3]
If you have time, will you please do one neutral dark grey theme?

RGB = 32, 32, 32
Hex = #202020

Or maybe you can tell me how to edit your theme. I have no coding experience.

**Comment by nekowinston** [comment]
You'd have to replace the occurrences of `#1e1e2e` with `#202020`, e.g. here: https://github.com/catppuccin/qbittorrent/blob/c2fa170731a17644a6f93d4d8fc4614426488c62/src/mocha/stylesheet.qss#L12

Then run the build script
https://github.com/catppuccin/qbittorrent/blob/main/tools/build.ps1
