### ISSUE TITLE
Theme issues with latest qbittorrent using QT 6

### ISSUE THREAD

**Issue by TheSparrowLenz** [catppuccin/qbittorrent#4]
I love using your themes and thank you so much for all the effort put into them. To make them even better, let me share an issue I have encountered with the FRAPPE theme on the latest qbittorrent using QT6.

**No background for the progress bar (same issue in Content tab)**
![image](https://user-images.githubusercontent.com/2780450/223978166-a9ec4312-f1c3-4906-a1d9-cda155b56963.png)

**Comment by Source-Dom** [comment]
rss feed is really hard to read also
![image](https://github.com/catppuccin/qbittorrent/assets/84047066/c8356edc-1f08-49d1-8424-ee2d1ebc2d8b)
