### ISSUE TITLE
Support v5.0.0 (alpha)

### ISSUE THREAD

**Issue by d47081** [catppuccin/qbittorrent#7]
Thanks for your work!

**Comment by Ejz85** [comment]
Yea would appreciate an update for 5.0.0. Uhm, the colors are all wrong now.

https://imgur.com/6eEuUCT

**Comment by sgoudham** [comment]
> Yea would appreciate an update for 5.0.0. Uhm, the colors are all wrong now.

I believe the current listed maintainer for this repository (@Xurdejl) is not active at the moment so PRs would definitely be appreciated.

**Comment by sgoudham** [comment]
Hey :wave:,

The recent [v2.0.0](https://github.com/catppuccin/qbittorrent/releases/tag/v2.0.0) release seems to work perfectly with the v5.0.0 alpha as demonstrated in the screenshot below:

![image](https://github.com/user-attachments/assets/8a8ee3f0-2353-469b-bc48-de2097a1f8b2)

I'll be closing this issue as resolved but feel free to re-open or create a new issue if you find that something is missing or incorrect in v5.0.0. Thanks!
