### ISSUE TITLE
What about the WebUI ?

### ISSUE THREAD

**Issue by Impre-visible** [catppuccin/qbittorrent#8]
Hi everyone, I want to enjoy catppuccin on qbittorrent, but I use the webui, cause qbittorent is on a docker container. So I would like to know if it was planned ? Thanks in advance

**Comment by nekowinston** [comment]
Hey there, this is a duplicate of #6; the previous maintainer is now inactive, I would appreciate if anyone else could pick this up; nothing is planned from our side.
