### ISSUE TITLE
icon bug in v4.6.2

### ISSUE THREAD

**Issue by drbobo0** [catppuccin/qbittorrent#9]
the icon bug :

<img width="686" alt="ScreenShot_20231209212110" src="https://github.com/catppuccin/qbittorrent/assets/40316129/6bbeb356-4486-4032-9098-85649adf288a">

the icon return to normal when u select it:

<img width="686" alt="ScreenShot_20231209212122" src="https://github.com/catppuccin/qbittorrent/assets/40316129/294e653f-9abb-46e0-8696-0e33775f96bc">

**Comment by Zorakie** [comment]
Can confirm, also happens in the Content details, see picture. Additionally, the margins/paddings in the details are different on hover, causing the text to jump a bit. 
![image](https://github.com/catppuccin/qbittorrent/assets/14437576/0580425e-6085-4e47-be2a-240894549b32)

**Comment by bastabro** [comment]
fix: just remove padding in the QTreeView::item section. if you like the hover motion just add padding: 2px in the QTreeView::item:hover, QTreeView::item:selected section.

**Comment by drbobo0** [comment]
> fix: just remove padding in the QTreeView::item section. if you like the hover motion just add padding: 2px in the QTreeView::item:hover, QTreeView::item:selected section.

thx it worked
[qbthemes.zip](https://github.com/catppuccin/qbittorrent/files/14552268/qbthemes.zip)

<img width="686" alt="ScreenShot_20240311010740" src="https://github.com/catppuccin/qbittorrent/assets/40316129/89bc1485-3354-48b0-a887-3ebee9d10a5d">

**Comment by ceeeej1141** [comment]
> > fix: just remove padding in the QTreeView::item section. if you like the hover motion just add padding: 2px in the QTreeView::item:hover, QTreeView::item:selected section.
> 
> thx it worked [qbthemes.zip](https://github.com/catppuccin/qbittorrent/files/14552268/qbthemes.zip)
> <img alt="ScreenShot_20240311010740" width="686" src="https://private-user-images.githubusercontent.com/40316129/311554398-89bc1485-3354-48b0-a887-3ebee9d10a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTE0NDYsIm5iZiI6MTcxMTI1MTE0NiwicGF0aCI6Ii80MDMxNjEyOS8zMTE1NTQzOTgtODliYzE0ODUtMzM1NC00OGIwLWE4ODctM2ViZWU5ZDEwYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzA2YmJkZjc4NTZmMTA1NWYzOThmMDdlNmNhYmMwNTY4YWQ5NDJjNDdmOWZjNWVjNzcwZjgzMjlhYzk0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNuEs-Q0wuGpK10vqTE3Eu41gZ5WOsgmm80Q_NCm0sw">

I tried this but the issue still persists (v4.6.3)

**Comment by drbobo0** [comment]
now it should work for all themes
 
[qbthemes.zip](https://github.com/catppuccin/qbittorrent/files/14734387/qbthemes.zip)


> > > fix: just remove padding in the QTreeView::item section. if you like the hover motion just add padding: 2px in the QTreeView::item:hover, QTreeView::item:selected section.
> > 
> > 
> > thx it worked [qbthemes.zip](https://github.com/catppuccin/qbittorrent/files/14552268/qbthemes.zip)
> > <img alt="ScreenShot_20240311010740" width="686" src="https://private-user-images.githubusercontent.com/40316129/311554398-89bc1485-3354-48b0-a887-3ebee9d10a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTE0NDYsIm5iZiI6MTcxMTI1MTE0NiwicGF0aCI6Ii80MDMxNjEyOS8zMTE1NTQzOTgtODliYzE0ODUtMzM1NC00OGIwLWE4ODctM2ViZWU5ZDEwYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzA2YmJkZjc4NTZmMTA1NWYzOThmMDdlNmNhYmMwNTY4YWQ5NDJjNDdmOWZjNWVjNzcwZjgzMjlhYzk0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNuEs-Q0wuGpK10vqTE3Eu41gZ5WOsgmm80Q_NCm0sw">
> 
> I tried this but the issue still persists (v4.6.3)
